import { Product, Category, NutrientMetadata } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'quesos-blandos',
    name: 'Quesos Blandos',
    icon: '🧀',
    description: 'Quesos de pasta blanda, ideales para untar, derretir o comer en ensaladas.'
  },
  {
    id: 'quesos-untables',
    name: 'Quesos Untables',
    icon: '🧈',
    description: 'Quesos para untar, procesados y fundidos. Analizados por su sodio y grasas trans.',
    isComingSoon: false
  },
  {
    id: 'yogures',
    name: 'Yogures Descremados',
    icon: '🥛',
    description: 'Yogures enteros y descremados analizados por su azúcar y proteínas.',
    isComingSoon: true
  },
  {
    id: 'panes',
    name: 'Panes de Molde',
    icon: '🍞',
    description: 'Panes lactales e integrales, evaluados por su fibra y conservantes.',
    isComingSoon: true
  },
  {
    id: 'galletas',
    name: 'Galletitas de Cereal',
    icon: '🍪',
    description: 'Galletitas dulces y saladas. Analizando harinas refinadas y grasas trans.',
    isComingSoon: true
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'tregar-por-salut-light-sin-sal',
    categoryId: 'quesos-blandos',
    puesto: 1,
    name: 'Por Salut Light Sin Sal',
    brand: 'Tregar',
    calories: 243,
    proteins: 29,
    totalFats: 13,
    saturatedFats: 7.0,
    transFats: 0,
    sodium: 37,
    calcium: 800,
    pricePerKg: 16985,
    recommendedSupermarkets: ['Carrefour', 'Comodín'],
    tier: 'S',
    badge: '🥇 1er Puesto - Súper Recomendado',
    nutritionistVerdict: '¡La opción estrella! Prácticamente libre de sodio (solo 37mg), altísimo en proteínas y con un aporte graso muy controlado. Excelente para hipertensos y descenso de peso.',
    imageUrl: '/quesos-blandos/01-S.png'
  },
  {
    id: 'la-serenisima-port-salut-sin-sal-light',
    categoryId: 'quesos-blandos',
    puesto: 2,
    name: 'Port Salut Sin Sal Light',
    brand: 'La Serenísima',
    calories: 217,
    proteins: 27,
    totalFats: 12,
    saturatedFats: 7.2,
    transFats: 0,
    sodium: 38,
    calcium: 932,
    pricePerKg: 25550,
    recommendedSupermarkets: ['La Anónima'],
    tier: 'A',
    badge: '🥈 2do Puesto - Nutrición Premium',
    nutritionistVerdict: 'Nutricionalmente impecable (solo 38mg de sodio y excelente calcio/proteína). Sin embargo, su precio es sumamente elevado en comparación con Tregar. Si el dinero no es traba, es un S-Tier.',
    imageUrl: '/quesos-blandos/02.png'
  },
  {
    id: 'la-serenisima-port-salut-light',
    categoryId: 'quesos-blandos',
    puesto: 3,
    name: 'Port Salut Light',
    brand: 'La Serenísima',
    calories: 218,
    proteins: 27,
    totalFats: 12,
    saturatedFats: 7.2,
    transFats: 0,
    sodium: 430,
    calcium: 932,
    pricePerKg: 15260,
    recommendedSupermarkets: ['Comodín'],
    tier: 'B',
    badge: '🥉 3er Puesto - Opción Equilibrada',
    nutritionistVerdict: 'Muy buen balance de proteínas (27g) y excelente cantidad de calcio (932mg, de los más altos). El sodio es intermedio, siendo una opción cotidiana muy sólida para la población general.',
    imageUrl: '/quesos-blandos/03.png'
  },
  {
    id: 'la-serenisima-cremon-light',
    categoryId: 'quesos-blandos',
    puesto: 4,
    name: 'Cremón Light',
    brand: 'La Serenísima',
    calories: 236,
    proteins: 21,
    totalFats: 17,
    saturatedFats: 11.0,
    transFats: 0.5,
    sodium: 340,
    calcium: 714,
    pricePerKg: 18190,
    recommendedSupermarkets: ['Comodín'],
    tier: 'C',
    badge: '🏅 4to Puesto - Aceptable',
    nutritionistVerdict: 'Su textura cremosa es excelente, pero ten cuidado: aunque dice "Light", posee 11g de grasas saturadas, sensiblemente mayor que las opciones superiores. Consumo moderado.',
    imageUrl: '/quesos-blandos/04.png'
  },
  {
    id: 'tregar-por-salut-dietetico-con-sal',
    categoryId: 'quesos-blandos',
    puesto: 5,
    name: 'Por Salut Dietético con Sal',
    brand: 'Tregar',
    calories: 233,
    proteins: 29,
    totalFats: 13,
    saturatedFats: 7.0,
    transFats: 0,
    sodium: 550,
    calcium: 800,
    pricePerKg: 14499,
    recommendedSupermarkets: ['Carrefour', 'Comodín'],
    tier: 'C',
    badge: '🏅 5to Puesto - Buena Proteína',
    nutritionistVerdict: 'Tiene un contenido de proteínas espectacular (29g) y un precio muy competitivo. No obstante, el sodio sube a 550mg. Es una gran alternativa económica si no tienes restricción de sal.',
    imageUrl: '/quesos-blandos/05.png'
  },
  {
    id: 'felices-las-vacas-muzzalmendra-vegano',
    categoryId: 'quesos-blandos',
    puesto: 6,
    name: 'Muzzalmendra (Vegano)',
    brand: 'Felices Las Vacas',
    calories: 273,
    proteins: 2,
    totalFats: 22,
    saturatedFats: 6.0,
    transFats: 0,
    sodium: 533,
    calcium: 'N/D',
    pricePerKg: 15020,
    recommendedSupermarkets: ['Carrefour (Tienda Digital)'],
    tier: 'C',
    badge: '🏅 6to Puesto - Alternativa Plant-Based',
    nutritionistVerdict: 'Es la mejor opción si llevas una dieta libre de lácteos o vegana. Es bajo en grasas saturadas (6g), pero ten en cuenta que casi no aporta proteínas (solo 2g) y el sodio es elevado.',
    imageUrl: '/quesos-blandos/06.png'
  },
  {
    id: 'la-serenisima-queso-protein',
    categoryId: 'quesos-blandos',
    puesto: 7,
    name: 'Queso Protein',
    brand: 'La Serenísima',
    calories: 191,
    proteins: 30,
    totalFats: 7.5,
    saturatedFats: 5.0,
    transFats: 0.2,
    sodium: 597,
    calcium: 955,
    pricePerKg: 25690,
    recommendedSupermarkets: ['Comodín', 'La Serenísima'],
    tier: 'D',
    badge: '🚨 7mo Puesto - Alerta Sodio y Costo',
    nutritionistVerdict: 'Es el más bajo en calorías y grasas de todos, y el más alto en proteínas (30g). Lamentablemente, posee un exceso notable de sodio (597mg) y un precio altísimo. Consumir de manera planificada.',
    imageUrl: '/quesos-blandos/07.png'
  },
  {
    id: 'la-serenisima-cremon-cremoso',
    categoryId: 'quesos-blandos',
    puesto: 8,
    name: 'Cremón Cremoso',
    brand: 'La Serenísima',
    calories: 290,
    proteins: 18,
    totalFats: 24,
    saturatedFats: 15.0,
    transFats: 0.7,
    sodium: 330,
    calcium: 642,
    pricePerKg: 18550,
    recommendedSupermarkets: ['Comodín'],
    tier: 'F',
    badge: '🚫 8vo Puesto - No Recomendado Diario',
    nutritionistVerdict: 'Porcentaje graso elevado (24g de grasas totales y 15g saturadas). No es adecuado para el consumo de todos los días, ya que aporta muchas calorías vacías de grasas saturadas.',
    imageUrl: '/quesos-blandos/08.png'
  },
  {
    id: 'la-serenisima-port-salut-clasico',
    categoryId: 'quesos-blandos',
    puesto: 9,
    name: 'Port Salut Clásico',
    brand: 'La Serenísima',
    calories: 305,
    proteins: 20,
    totalFats: 25,
    saturatedFats: 15.0,
    transFats: 0.7,
    sodium: 370,
    calcium: 807,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🚫 9no Puesto - No Recomendado',
    nutritionistVerdict: 'El queso clásico tiene un tenor graso elevado (15g saturadas) que perjudica tu perfil lipídico si se consume en demasía. Reemplaza siempre por su equivalente Light de la misma marca.',
    imageUrl: '/quesos-blandos/09.png'
  },
  {
    id: 'tregar-por-salut',
    categoryId: 'quesos-blandos',
    puesto: 10,
    name: 'Por Salut Clásico',
    brand: 'Tregar',
    calories: 323,
    proteins: 20,
    totalFats: 27,
    saturatedFats: 16.0,
    transFats: 1.3,
    sodium: 437,
    calcium: 653,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🚫 10mo Puesto - No Recomendado',
    nutritionistVerdict: 'Muy alto en calorías (323) y grasas saturadas (16g) comparado con su versión Light. No se justifica nutricionalmente existiendo la alternativa Light Sin Sal de la misma firma.',
    imageUrl: '/quesos-blandos/10.png'
  },
  {
    id: 'tregar-cremoso',
    categoryId: 'quesos-blandos',
    puesto: 11,
    name: 'Cremoso Clásico',
    brand: 'Tregar',
    calories: 337,
    proteins: 19,
    totalFats: 29,
    saturatedFats: 17.0,
    transFats: 1.7,
    sodium: 483,
    calcium: 647,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🚫 11er Puesto - Evitar en Dieta Habitual',
    nutritionistVerdict: 'El menos saludable de la comparativa. Es el que tiene más calorías (337) y más grasas saturadas (17g) de todo el catálogo, además de un sodio considerable. Reservar únicamente para ocasiones especiales.',
    imageUrl: '/quesos-blandos/11.png'
  },
  {
    id: 'casancrem-light-sin-sal',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Casancrem Light Sin Sal Agregada',
    brand: 'Casancrem',
    calories: 120,
    proteins: 8,
    totalFats: 5.7,
    saturatedFats: 3.7,
    transFats: 0,
    sodium: 97,
    calcium: 183,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Sin TACC. Sin sal agregada. Contiene almidón modificado y estabilizantes.',
    imageUrl: '/quesos-untables/Casancrem Light Sin Sal Agregada.png'
  },
  {
    id: 'cremette-light-tonadita',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Cremette Light',
    brand: 'Tonadita',
    calories: 150,
    proteins: 5.7,
    totalFats: 9.7,
    saturatedFats: 5.7,
    transFats: 0,
    sodium: 560,
    calcium: 'N/D',
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Sin TACC. Queso procesado con crema. Alta presencia de estabilizantes.',
    imageUrl: '/quesos-untables/Cremette Light (Tonadita).png'
  },
  {
    id: 'cremon-untable-light',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Cremón Untable Light',
    brand: 'La Serenísima',
    calories: 137,
    proteins: 10,
    totalFats: 6.7,
    saturatedFats: 4.7,
    transFats: 0,
    sodium: 113,
    calcium: 257,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Sin TACC. Excelente aporte proteico.',
    imageUrl: '/quesos-untables/Cremón Untable Light (La Serenísima).png'
  },
  {
    id: 'cremon-untable-original',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Cremón Untable Original',
    brand: 'La Serenísima',
    calories: 150,
    proteins: 8.7,
    totalFats: 9.7,
    saturatedFats: 5.7,
    transFats: 0,
    sodium: 117,
    calcium: 263,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Sin TACC. Perfil de sodio muy controlado.',
    imageUrl: '/quesos-untables/Cremón Untable Original (La Serenísima).png'
  },
  {
    id: 'finlandia-mas-liviano',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Finlandia Más Liviano',
    brand: 'La Serenísima',
    calories: 130,
    proteins: 9,
    totalFats: 8,
    saturatedFats: 5,
    transFats: 0,
    sodium: 63,
    calcium: 266,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Perfil extremadamente bajo en sodio. Excelente aporte de proteínas y calcio.',
    imageUrl: '/quesos-untables/Finlandia Más Liviano (La Serenísima).png'
  },
  {
    id: 'finlandia-light',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Finlandia Light',
    brand: 'La Serenísima',
    calories: 190,
    proteins: 9,
    totalFats: 14.7,
    saturatedFats: 9.7,
    transFats: 0,
    sodium: 180,
    calcium: 366,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Buen aporte proteico y el nivel más alto de calcio de la lista.',
    imageUrl: '/quesos-untables/Finlandia Light (La Serenísima).png'
  },
  {
    id: 'blanco-light-tregar',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Blanco Light',
    brand: 'Tregar',
    calories: 147,
    proteins: 12.3,
    totalFats: 9.3,
    saturatedFats: 6,
    transFats: 0.3,
    sodium: 50,
    calcium: 'N/D',
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Increíble perfil proteico y mínimo sodio.',
    imageUrl: '/quesos-untables/Blanco Light (Tregar).png'
  },
  {
    id: 'chatel-tregar',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Chatel',
    brand: 'Tregar',
    calories: 153,
    proteins: 16.7,
    totalFats: 8.7,
    saturatedFats: 5.7,
    transFats: 0,
    sodium: 533,
    calcium: 567,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Récord absoluto en proteínas y calcio para la categoría.',
    imageUrl: '/quesos-untables/Chatel (Tregar).png'
  },
  {
    id: 'por-salut-equilibrio',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Por Salut Equilibrio',
    brand: 'La Paulina',
    calories: 140,
    proteins: 14,
    totalFats: 6.7,
    saturatedFats: 4.3,
    transFats: 0,
    sodium: 893,
    calcium: 'N/D',
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Proteína excelente, pero con niveles críticos de sodio. Sello frontal de exceso.',
    imageUrl: '/quesos-untables/Por Salut Equilibrio (La Paulina).png'
  },
  {
    id: 'por-salut-la-paulina',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Por Salut',
    brand: 'La Paulina',
    calories: 170,
    proteins: 10.7,
    totalFats: 11.3,
    saturatedFats: 6.7,
    transFats: 0,
    sodium: 646,
    calcium: 'N/D',
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Sellos frontales de Exceso en Sodio y Exceso en Grasas Saturadas. Perfil pesado.',
    imageUrl: '/quesos-untables/Por Salut (La Paulina).png'
  },
  {
    id: 'crema-equilibrio',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Crema Equilibrio',
    brand: 'La Paulina',
    calories: 110,
    proteins: 5.7,
    totalFats: 5.3,
    saturatedFats: 3.3,
    transFats: 0,
    sodium: 293,
    calcium: 'N/D',
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Muy bajo en calorías y grasas absolutas. Bajo aporte proteico.',
    imageUrl: '/quesos-untables/Crema Equilibrio (La Paulina).png'
  },
  {
    id: 'crema-tradicional',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Crema Tradicional',
    brand: 'La Paulina',
    calories: 246,
    proteins: 4.3,
    totalFats: 22,
    saturatedFats: 14,
    transFats: 1,
    sodium: 256,
    calcium: 'N/D',
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Alto en grasas totales, saturadas y trans. Perfil proteico muy pobre.',
    imageUrl: '/quesos-untables/Crema Tradicional (La Paulina).png'
  },
  {
    id: 'cream-cheese-santa-clara',
    categoryId: 'quesos-untables',
    puesto: 0,
    name: 'Cream Cheese',
    brand: 'Santa Rosa',
    calories: 180,
    proteins: 10,
    totalFats: 11,
    saturatedFats: 7.7,
    transFats: 0,
    sodium: 170,
    calcium: 463,
    pricePerKg: 'N/D',
    recommendedSupermarkets: [],
    tier: 'F',
    badge: '🔄 Analizando...',
    nutritionistVerdict: 'Buen balance proteico y excelente aporte de calcio.',
    imageUrl: '/quesos-untables/Cream Cheese (Santa Rosa).png'
  }
];

export const TIER_DETAILS = {
  S: { name: 'S-Tier', color: 'from-emerald-500 to-teal-600', text: 'text-emerald-700 bg-emerald-50 border-emerald-200', desc: 'Opción Excelente: Bajo en sodio, baja grasa, alto en proteína.' },
  A: { name: 'A-Tier', color: 'from-green-400 to-emerald-500', text: 'text-green-700 bg-green-50 border-green-200', desc: 'Muy Recomendable: Buena calidad, ideal si buscas alternativas (vegano/bajos).' },
  B: { name: 'B-Tier', color: 'from-blue-400 to-indigo-500', text: 'text-blue-700 bg-blue-50 border-blue-200', desc: 'Opción Equilibrada: Bueno para uso general diario.' },
  C: { name: 'C-Tier', color: 'from-amber-400 to-orange-500', text: 'text-amber-700 bg-amber-50 border-amber-200', desc: 'Consumo Moderado: Detalles a vigilar (sodio elevado o grasa intermedia).' },
  D: { name: 'D-Tier', color: 'from-orange-500 to-red-400', text: 'text-orange-700 bg-orange-50 border-orange-200', desc: 'Consumo Ocasional: Vigilar por alto contenido de sodio o precio excesivo.' },
  F: { name: 'F-Tier', color: 'from-red-500 to-rose-600', text: 'text-rose-700 bg-rose-50 border-rose-200', desc: 'Evitar Diario: Demasiado graso o calórico. Preferir sustitutos light.' }
};

export const NUTRIENTS_METADATA: NutrientMetadata[] = [
  { key: 'calories', label: 'Calorías', unit: 'kcal', betterDirection: 'lower', description: 'Menor es mejor para control de peso.' },
  { key: 'proteins', label: 'Proteínas', unit: 'g', betterDirection: 'higher', description: 'Mayor es mejor para saciedad y músculo.' },
  { key: 'saturatedFats', label: 'Grasas Sat.', unit: 'g', betterDirection: 'lower', description: 'Menos cantidad protege el sistema cardiovascular.' },
  { key: 'transFats', label: 'Grasas Trans', unit: 'g', betterDirection: 'lower', description: 'Se recomienda evitar lo máximo posible.' },
  { key: 'sodium', label: 'Sodio', unit: 'mg', betterDirection: 'lower', description: 'Menos es mejor para la presión arterial.' },
  { key: 'calcium', label: 'Calcio', unit: 'mg', betterDirection: 'higher', description: 'Fundamental para la salud ósea.' },
  { key: 'pricePerKg', label: 'Precio/Kg', unit: '$', betterDirection: 'lower', description: 'Indicador económico.' }
];
